// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kmers
List kmers(const CharacterVector& x, int k, bool simplify, bool anchor, bool clean_up, bool key_as_int, bool starting_index);
RcppExport SEXP _molMIC_kmers(SEXP xSEXP, SEXP kSEXP, SEXP simplifySEXP, SEXP anchorSEXP, SEXP clean_upSEXP, SEXP key_as_intSEXP, SEXP starting_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type simplify(simplifySEXP);
    Rcpp::traits::input_parameter< bool >::type anchor(anchorSEXP);
    Rcpp::traits::input_parameter< bool >::type clean_up(clean_upSEXP);
    Rcpp::traits::input_parameter< bool >::type key_as_int(key_as_intSEXP);
    Rcpp::traits::input_parameter< bool >::type starting_index(starting_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(kmers(x, k, simplify, anchor, clean_up, key_as_int, starting_index));
    return rcpp_result_gen;
END_RCPP
}
// kmers_to_libsvm
bool kmers_to_libsvm(const CharacterVector& x, const CharacterVector& target_path, const CharacterVector& label, int k);
RcppExport SEXP _molMIC_kmers_to_libsvm(SEXP xSEXP, SEXP target_pathSEXP, SEXP labelSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type target_path(target_pathSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type label(labelSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(kmers_to_libsvm(x, target_path, label, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_molMIC_kmers", (DL_FUNC) &_molMIC_kmers, 7},
    {"_molMIC_kmers_to_libsvm", (DL_FUNC) &_molMIC_kmers_to_libsvm, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_molMIC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
