# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generates genome kmers
#'
#' @param x genome in string format
#' @param k kmer length
#' @param simplify returns a numeric vector of kmer counts, without associated string. This is useful to save memory, but should always be used with anchor = true
#'
#' @return list of kmer values
kmers <- function(x, k = 3L, simplify = FALSE, anchor = TRUE, clean_up = TRUE, key_as_int = FALSE, starting_index = 1L) {
    .Call('_molMIC_kmers', PACKAGE = 'molMIC', x, k, simplify, anchor, clean_up, key_as_int, starting_index)
}

